**Objetivo:** repetir con un dataset diferente las operaciones vistas con Pingüinos: explorar, seleccionar, filtrar, agrupar, limpiar, transformar y exportar.

**Importante:** usa el material de referencia, documentación y, si lo deseas, un asistente de IA. Debes **entender y comprobar** el código. Las celdas están intencionadamente sin resolver.

In [15]:
import pandas as pd
iris = pd.read_csv("iris_con_faltantes.csv")    
     
print("Dataset cargado:", iris.shape)
display(iris.head(3))

Dataset cargado: (150, 5)

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa

**Comprobación esperada:** `(150, 5)`.

**Referencia de columnas:** `sepal_length_cm`, `sepal_width_cm`, `petal_length_cm`, `petal_width_cm`, `species`. Las medidas están expresadas en centímetros.

## Ejercicio 1. Explorar el dataset

a) Muestra las primeras cinco filas. b) Identifica las dimensiones. c) Consulta los tipos de columna y sus valores no nulos. d) Encuentra cuáles especies aparecen en la columna `species`.

**Pista:** Recuerda `head`, `shape`, `info` y `unique`. Debes encontrar **3 especies**.

In [16]:
display(iris.head(5))
print(iris.shape)
iris.info()
print(iris["species"].unique())

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             NaN              1.4             0.2  setosa

(150, 5)
<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sepal_length_cm  150 non-null    float64
 1   sepal_width_cm   145 non-null    float64
 2   petal_length_cm  150 non-null    float64
 3   petal_width_cm   147 non-null    float64
 4   species          150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB
<StringArray>
['setosa', 'versicolor', 'virginica']
Length: 3, dtype: str

## Ejercicio 2. Seleccionar columnas y posiciones

a) Crea una tabla que contenga solo `species` y `petal_length_cm`. b) Muestra **las cinco primeras filas y las dos primeras columnas** mediante posiciones, no nombres.

**Pista:** Usa una lista de columnas para (a) y `iloc` para (b). El final de un slice no se incluye.

In [17]:
display(iris[["species", "petal_length_cm"]])
display(iris.iloc[:5, :2])

       species  petal_length_cm
0       setosa              1.4
1       setosa              1.4
2       setosa              1.3
3       setosa              1.5
4       setosa              1.4
..         ...              ...
145  virginica              5.2
146  virginica              5.0
147  virginica              5.2
148  virginica              5.4
149  virginica              5.1

[150 rows x 2 columns]

   sepal_length_cm  sepal_width_cm
0              5.1             3.5
1              4.9             3.0
2              4.7             3.2
3              4.6             3.1
4              5.0             NaN

## Ejercicio 3. Filtrar con una o dos condiciones

a) Selecciona solamente flores de la especie `setosa`. b) Selecciona flores de `virginica` cuyo `petal_length_cm` sea **mayor que 5.5**. c) Muestra cuántas filas tiene cada resultado.

**Pista:** Utiliza una máscara de comparación y `&`; cada condición debe ir entre paréntesis.

In [18]:
setosa = iris[iris["species"] == "setosa"]
virginica_largo = iris[(iris["species"] == "virginica") & (iris["petal_length_cm"] > 5.5)]

display(setosa)
print("Filas de setosa:", len(setosa))

display(virginica_largo)
print("Filas de virginica con pétalo > 5.5:", len(virginica_largo))

    sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0               5.1             3.5              1.4             0.2  setosa
1               4.9             3.0              1.4             0.2  setosa
2               4.7             3.2              1.3             0.2  setosa
3               4.6             3.1              1.5             0.2  setosa
4               5.0             NaN              1.4             0.2  setosa
5               5.4             3.9              1.7             0.4  setosa
6               4.6             3.4              1.4             0.3  setosa
7               5.0             3.4              1.5             0.2  setosa
8               4.4             2.9              1.4             0.2  setosa
9               4.9             3.1              1.5             0.1  setosa
10              5.4             3.7              1.5             0.2  setosa
11              4.8             3.4              1.6             0.2  setosa
12              4.8             3.0              1.4             NaN  setosa
13              4.3             3.0              1.1             0.1  setosa
14              5.8             4.0              1.2             0.2  setosa
15              5.7             4.4              1.5             0.4  setosa
16              5.4             3.9              1.3             0.4  setosa
17              5.1             3.5              1.4             0.3  setosa
18              5.7             3.8              1.7             0.3  setosa
19              5.1             3.8              1.5             0.3  setosa
20              5.4             3.4              1.7             0.2  setosa
21              5.1             3.7              1.5             0.4  setosa
22              4.6             3.6              1.0             0.2  setosa
23              5.1             3.3              1.7             0.5  setosa
24              4.8             3.4              1.9             0.2  setosa
25              5.0             3.0              1.6             0.2  setosa
26              5.0             3.4              1.6             0.4  setosa
27              5.2             3.5              1.5             0.2  setosa
28              5.2             3.4              1.4             0.2  setosa
29              4.7             3.2              1.6             0.2  setosa
30              4.8             3.1              1.6             0.2  setosa
31              5.4             3.4              1.5             0.4  setosa
32              5.2             4.1              1.5             0.1  setosa
33              5.5             4.2              1.4             0.2  setosa
34              4.9             3.1              1.5             0.2  setosa
35              5.0             3.2              1.2             0.2  setosa
36              5.5             3.5              1.3             0.2  setosa
37              4.9             NaN              1.4             0.1  setosa
38              4.4             3.0              1.3             0.2  setosa
39              5.1             3.4              1.5             0.2  setosa
40              5.0             3.5              1.3             0.3  setosa
41              4.5             2.3              1.3             0.3  setosa
42              4.4             3.2              1.3             0.2  setosa
43              5.0             3.5              1.6             0.6  setosa
44              5.1             3.8              1.9             0.4  setosa
45              4.8             3.0              1.4             0.3  setosa
46              5.1             3.8              1.6             0.2  setosa
47              4.6             3.2              1.4             0.2  setosa
48              5.3             3.7              1.5             0.2  setosa
49              5.0             3.3              1.4             0.2  setosa

Filas de setosa: 50

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,species
100,6.3,3.3,6.0,NaN,virginica
102,7.1,3.0,5.9,2.1,virginica
103,6.3,2.9,5.6,1.8,virginica
104,6.5,3.0,5.8,2.2,virginica
105,7.6,3.0,6.6,2.1,virginica
107,7.3,2.9,6.3,1.8,virginica
108,6.7,2.5,5.8,1.8,virginica
109,7.2,3.6,6.1,2.5,virginica
117,7.7,3.8,6.7,2.2,virginica
118,7.7,2.6,6.9,2.3,virginica
120,6.9,NaN,5.7,2.3,virginica
122,7.7,2.8,6.7,2.0,virginica
124,6.7,3.3,5.7,2.1,virginica
125,7.2,3.2,6.0,1.8,virginica
128,6.4,2.8,5.6,2.1,virginica
129,7.2,3.0,5.8,1.6,virginica
130,7.4,2.8,6.1,1.9,virginica
131,7.9,3.8,6.4,2.0,virginica
132,6.4,2.8,5.6,2.2,virginica
134,6.1,2.6,5.6,1.4,virginica
135,7.7,3.0,6.1,2.3,virginica
136,6.3,3.4,5.6,2.4,virginica
140,6.7,3.1,5.6,2.4,virginica
143,6.8,3.2,5.9,2.3,virginica
144,6.7,3.3,5.7,2.5,virginica

Filas de virginica con pétalo > 5.5: 25

## Ejercicio 4. Contar y agrupar por especie

a) Cuenta cuántas flores hay de cada especie. b) Calcula el **promedio de `petal_length_cm` para cada especie**. c) Identifica cuál tiene el promedio mayor.

**Pista:** Busca `value_counts`, `groupby` y `mean`. La columna `petal_length_cm` no contiene faltantes en esta copia.

In [19]:
print(iris["species"].value_counts())

promedios = iris.groupby("species")["petal_length_cm"].mean()
print(promedios)

print("Especie con mayor promedio:", promedios.idxmax())

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64
species
setosa        1.462
versicolor    4.260
virginica     5.552
Name: petal_length_cm, dtype: float64
Especie con mayor promedio: virginica

## Ejercicio 5. Limpiar valores faltantes y quitar columnas

a) Cuenta cuántos valores faltan por columna. b) Crea **una copia** sin las filas que tengan valores vacíos y cuenta cuántas quedan. c) Crea otra copia donde rellenes únicamente los faltantes de `sepal_width_cm` con su mediana. d) Crea una tercera copia sin la columna `petal_width_cm`. **No modifiques `iris` directamente.**

**Pista:** Recuerda `isna().sum()`, `dropna()`, `fillna()`, `median()` y `drop(columns=[...])`. Esperamos **142 filas completas** antes de rellenar.

In [20]:
print(iris.isna().sum())

copia_sin_nulos = iris.dropna()
print("Filas restantes:", len(copia_sin_nulos))

copia_rellenada = iris.copy()
copia_rellenada["sepal_width_cm"] = copia_rellenada["sepal_width_cm"].fillna(copia_rellenada["sepal_width_cm"].median())

copia_sin_columna = iris.drop(columns=["petal_width_cm"])

sepal_length_cm    0
sepal_width_cm     5
petal_length_cm    0
petal_width_cm     3
species            0
dtype: int64
Filas restantes: 142

## Ejercicio 6. Transformar columnas

a) Crea en una copia una nueva columna `petal_length_mm` convirtiendo centímetros a milímetros. b) Crea otra columna `species_codigo` asignando `S`, `V` y `G` a las tres especies. c) Comprueba cinco filas.

**Pista:** Para la conversión basta una operación sobre toda la columna; para códigos puedes usar `.map()` con un diccionario. Si quieres, prueba también `.apply(lambda ...)`.

In [21]:
df_transformado = iris.copy()
df_transformado["petal_length_mm"] = df_transformado["petal_length_cm"] * 10
df_transformado["species_codigo"] = df_transformado["species"].map({"setosa": "S", "versicolor": "V", "virginica": "G"})

display(df_transformado.head(5))

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,species,petal_length_mm,species_codigo
0,5.1,3.5,1.4,0.2,setosa,14.0,S
1,4.9,3.0,1.4,0.2,setosa,14.0,S
2,4.7,3.2,1.3,0.2,setosa,13.0,S
3,4.6,3.1,1.5,0.2,setosa,15.0,S
4,5.0,NaN,1.4,0.2,setosa,14.0,S

## Ejercicio 7. Exportar el resultado

a) Guarda el DataFrame transformado del ejercicio 6 en `iris_procesado.csv`, **sin guardar la columna de índice**. b) Vuelve a leer el CSV con Pandas y comprueba que conserva 150 filas y las nuevas columnas.

**Pista:** Usa `to_csv` con `index=False` y después `read_csv`.

In [22]:
df_transformado.to_csv("iris_procesado.csv", index=False)

iris_procesado = pd.read_csv("iris_procesado.csv")
print("Dimensiones:", iris_procesado.shape)
display(iris_procesado.head(5))

Dimensiones: (150, 7)

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,species,petal_length_mm,species_codigo
0,5.1,3.5,1.4,0.2,setosa,14.0,S
1,4.9,3.0,1.4,0.2,setosa,14.0,S
2,4.7,3.2,1.3,0.2,setosa,13.0,S
3,4.6,3.1,1.5,0.2,setosa,15.0,S
4,5.0,NaN,1.4,0.2,setosa,14.0,S

## Ejercicio 8. Unir filas con `concat`

a) Construye dos DataFrames: primeras 50 filas y siguientes 50 filas de `iris`. b) Únelos verticalmente y comprueba el número total de filas.

**Pista:** Combina `iloc` y `pd.concat`; prueba `ignore_index=True`.

In [23]:
df1 = iris.iloc[:50]
df2 = iris.iloc[50:100]

df_unido = pd.concat([df1, df2], ignore_index=True)
print("Número total de filas:", len(df_unido))

Número total de filas: 100

## Ejercicio 9. Relacionar tablas con `merge`
Crea una tabla pequeña con las columnas `species` y `codigo`: setosa→S, versicolor→V y virginica→G. Une esta tabla con `iris` mediante la especie. Verifica que aparecen 150 filas y una columna adicional. Los códigos son solamente etiquetas didácticas.

**Pista:** Puedes construir la tabla auxiliar con `pd.DataFrame({...})` y hacer un `merge` por `species`.

In [24]:
tabla_codigos = pd.DataFrame({
    "species": ["setosa", "versicolor", "virginica"],
    "codigo": ["S", "V", "G"]
})

iris_merged = pd.merge(iris, tabla_codigos, on="species")
print("Dimensiones:", iris_merged.shape)
display(iris_merged.head(5))

Dimensiones: (150, 6)

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,species,codigo
0,5.1,3.5,1.4,0.2,setosa,S
1,4.9,3.0,1.4,0.2,setosa,S
2,4.7,3.2,1.3,0.2,setosa,S
3,4.6,3.1,1.5,0.2,setosa,S
4,5.0,NaN,1.4,0.2,setosa,S

## Antes de entregar
**Guarde en un Github creado Público** `git status` → `git add .` → `git commit -m "Practicar consultas y transformaciones con Pandas"`. Evita subir al repositorio archivos de entornos virtuales (`.venv/`).